# Development environment values
replicaCount: 1

image:
  repository: nginx
  tag: "1.21"
  pullPolicy: Always

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: myapp-dev.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

# Development specific configuration
config:
  env:
    - name: NODE_ENV
      value: "development"
    - name: LOG_LEVEL
      value: "debug"
    - name: PORT
      value: "8080"

# Enable verbose health checks for development
probes:
  liveness:
    enabled: true
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 5
  readiness:
    enabled: true
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 3
