{{- if .Values.autoscaling.enabled }}
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "basic-application.fullname" . }}-config
  labels:
    {{- include "basic-application.labels" . | nindent 4 }}
data:
  # Add your configuration files here
  app.properties: |
    # Application configuration
    server.port=8080
    management.endpoints.web.exposure.include=health,info,metrics
    
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
{{- end }}
